[window]
opacity = 0.95
padding.x = 10
padding.y = 10
decorations = "none"
dynamic_padding = false

[font]
size = 11.0

[font.normal]
family = "Hurmit Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hurmit Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hurmit Nerd Font Mono"
style = "Italic"

[colors.primary]
background = "#1d1d1d"
foreground = "#e8e8e8"

[colors.cursor]
text = "#1d1d1d"
cursor = "#e8e8e8"

[colors.selection]
text = "#e8e8e8"
background = "#404040"

[colors.normal]
black = "#1a1a1a"
red = "#8b6b6b"
green = "#6b8b6b"
yellow = "#8b8b6b"
blue = "#6b6b8b"
magenta = "#8b6b8b"
cyan = "#6b8b8b"
white = "#e8e8e8"

[colors.bright]
black = "#404040"
red = "#b89090"
green = "#90b890"
yellow = "#b8b890"
blue = "#9090b8"
magenta = "#b890b8"
cyan = "#90b8b8"
white = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "EaseOutExpo"
duration = 0

[terminal.shell]
program = "/bin/bash"
args = ["-l"]


