add_newline = false
command_timeout = 1000

format = """
$character\
[î‚¼](fg:white bg:#5f6a8e)\
[â–ˆ](fg:#5f6a8e bg:black)\
$directory\
[â–ˆî‚¼](fg:#5f6a8e bg:#414868)\
[$git_branch\
$git_state\
$git_status](bold bg:#414868 fg:white)\
[î‚¼](fg:#414868 bg:#282a34)\
$fill\
$cmd_duration\
[î‚¸](fg:#2e2f38 bg:bright-black)\
[î‚¸](fg:bright-black bg:#fb4183)\
[â–ˆ](fg:#fb4183)\
[ï€‡ ](fg:black bg:#fb4183)\
[â–ˆ](fg:#fb4183)\
$username\
[î‚¸](fg:bright-black bg:#bd93f9)\
[â–ˆ](fg:#bd93f9)\
[ó°Œ½ ](fg:#bd93f9 bg:black inverted)\
[â–ˆ](fg:#bd93f9)\
$hostname\
$line_break\
[â€Ž]()"""

[character]
format = "$symbol"
error_symbol = "[â–ˆ](fg:red bg:black)[ï‹“ ERROR](fg:red bg:black inverted bold)[î‚¼](fg:red bg:white)"
success_symbol = "[â–ˆ](fg:bright-white bg:black)[îž• PROMPT](fg:bright-white bg:black inverted bold)[î‚¼](fg:bright-white bg:white)"

[fill]
symbol = ' '
style = 'bg:#282a34'

[package]
disabled = false

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format="[ó°žŒ $duration ]($style)"
style="bold bg:#2E2F38"

[directory]
truncation_length = 5
format = "[ó°‰‹ $path]($style)[$lock_symbol]($lock_style)"
style = "bold fg:bright-white bg:#5f6a8e"
read_only = "ðŸ”’"
read_only_style= "bold white"

[username]
show_always = true
style_user = "fg:bright-white bg:bright-black"
style_root = "fg:bright-white bg:bright-black"
format = '[ Moon ]($style)'

[hostname]
format = "[ Debian ]($style)"
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "fg:bright-white bg:bright-black"

[git_commit]
commit_hash_length = 8
style = "bold white"

[status]
style = "bg:transparent"
symbol = "ðŸ’¥ "
format = '($style)'
disabled = false

[git_branch]
format = " ó°˜¬ $branch"
style = "bold fg:bright-black bg:#3d4052"

[git_status]
format = " $conflicted$untracked$modified$staged$renamed$deleted$ahead_behind$stashed"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "cyan"
